### ISSUE TITLE
Make the getter strategy more intuitive

### ISSUE THREAD

**Issue by DoNormal** [zicht/itertools#21]
It would be nice if the getter strategy would also support getter functions for private fields, instead of expecting the precise name of the getter function.

Example:
```
class Melp
{
    private $value;
    public function getValue()
    {
        return $this->value;
    }
}
```

```
// Does not work
$result = iter\iterable($array)->sorted('value');

// Works, but is less intuitive
$result = iter\iterable($array)->sorted('getValue');
```

**Comment by boudewijn-zicht** [comment]
I believe the Symfony property access could be a very good alternative to the current implementation of `mixed_to_value_getter` (see https://github.com/zicht/itertools/blob/master/src/Zicht/Itertools/conversions.php#L110).

This property getter seems very complete.  I'll need to see how compatible it is with how Itertools has been working so far.

https://symfony.com/doc/current/components/property_access.html

**Comment by boudewijn-zicht** [comment]
https://github.com/zicht/itertools/tree/feature/use-symfony-property-access

Using the symfony property getter is my preferred solution, however, before you could access array keys using `$strategy = 'key'`,  unfortunately this is not the way array key access works in the symfony property access (this uses `$strategy = '[key]'`).

Hence, this will not be backwards compatible.  Hence not a good idea right now.

**Comment by boudewijn-zicht** [comment]
Instead of using symfony propery access (which would not be backwards compatible), I've implemented the same strategy used by Twig, which is backwards compatible.
